export const UNKNOWN_ERROR = "UNKNOWN_ERROR";
export const VALIDATION_ERROR = "VALIDATION_ERROR";

export const EMAIL_ALREADY_TAKEN = "EMAIL_ALREADY_TAKEN";

export const EMAIL_NOT_FOUND = "EMAIL_NOT_FOUND";
export const INVALID_CREDENTIALS = "INVALID_CREDENTIALS";
